pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
          agent {
              docker {
                 image 'snakee/golang-junit:1.21'
                 reuseNode true
              }
          }
            steps {
                dir('bugtracker-backend'){
                FROM golang:latest
                RUN mkdir -p /.cache && chmod -R 777 /.cache
                sh 'go test -v ./...'
             }
            }
        }
    }
}
