pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
          agent {
              docker {
                 image 'snakee/golang-junit:1.21'
                 reuseNode true
              }
          }
            steps {
                dir('bugtracker-backend'){
                    ENV GOCACHE=/tmp/go-build-cache
                       sh 'go test -v ./...'
             }
            }
        }
    }
}
